# Generated by Django 5.0.14 on 2025-04-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="location",
            field=models.CharField(
                blank=True,
                default="Not mentioned by the seller",
                max_length=200,
                null=True,
            ),
        ),
    ]
